### PR TITLE
Remove Debian 8, add Debian 10

### PR DESCRIPTION
**Pull request by argilo**
Debian 8 (Jessie) is unsupported, so we may as well remove it from the test suite. I've added ~~Debian 9 (Stretch) and~~ Debian 10 (Buster) instead, ~~both~~ using Python 3 and modelled after the Ubuntu 20.04 Dockerfile.

### CODE REVIEW

**Comment by jkbecker** [comment]
Sounds good to me. I cannot test it right now, but assuming you did feel free to merge.

**Review by jkbecker — APPROVED** [review]

**Comment by argilo** [comment]
I'm waiting for the installs to complete now, and will merge if everything checks out.

**Comment by jkbecker** [comment]
btw, should we deprecate/remove https://github.com/gnuradio/pybombs/blob/master/debian.md and close #498? They both refer to Jessie specifically.

**Comment by argilo** [comment]
Good point, I'll remove the references to Jessie in this pull request as well.

**Comment by argilo** [comment]
Debian 9 fails because its cmake is too old to build libvolk:
```
CMake Error at CMakeLists.txt:21 (cmake_minimum_required):
  CMake 3.8 or higher is required.  You are running version 3.7.2
```

**Comment by argilo** [comment]
I think I'll just remove Debian 9 from this pull request.

**Comment by jkbecker** [comment]
Honestly, this kind of stuff has wasted literal weeks of effort in my lab (multiple undergrads struggling with setups on different debian9-based machines)... Personally I'll be happy to see cmake-incompatible distros go (as in: not "officially supported"). Manually installing cmake from source + patching a bunch of other things works to fix this, but it is super cumbersome and annoying.
I'd say kick it out - especially if we want to consider pybombs as a "cutting-edge development enabler" rather than a "support everything" platform.

**Pull request merged**
