### PR TITLE
Handle ssh location when using git.

### PR DESCRIPTION
**Pull request by gr-sp**
Commit https://github.com/gnuradio/pybombs/commit/e756d7f2a3b3f3c6f433561c77680b7e2bed74d7 fails to parse a location of the form:
```
pybombs recipes add <alias> git+<username>@<IP|HOSTNAME>:<path/to/repo.git>@<commit|rev|tag>
```
Please reopen #358

My regex foo isn't great, but this commit handles both (normal and SSH) cases.

### CODE REVIEW

**Comment by gr-sp** [comment]
I cleaned up parse_git_url(...) by using the following regex:
```
(\S*)@((?!\S*[:*])\S*$)
```
which basically says that `@<hash>` must occur at the end of the input URL and it cannot contain `:` or whitespace. I tested it on the following URLs:
```
git@me:loc/repo.git@hash
git@me:repo.git@hash
git@me:loc/repo.git
http://loc/repo.git@hash
http://loc/repo.git
git@me:repo.git@hash
```
(https://regex101.com/r/yC0bE2/1)

**Comment by gr-sp** [comment]
Hmmm...this fails on the following formats at the moment:
```
ssh://[user@]host.xz/path/to/repo.git/
```
Lemme see if I can fix it.

**Comment by mbr0wn** [comment]
Not sure if we can have a single regex to catch them all (I mean, you always can, but maybe it's not the most readable.

Minus the whitespace, the current regex looks for @ followed by not :, until the end. I tested it on URLs like `git@me:loc/repo.git@hash`.

**Comment by mbr0wn** [comment]
I added a second layer of regexes. Think this should work.

**Comment by gr-sp** [comment]
Thanks for that. Everything seems to be working. I got a little side-tracked yesterday.

**Comment by mbr0wn** [comment]
No problem. I'm a bit antsy because I really want to tag that release.

**Comment by mbr0wn** [comment]
...thanks for the insane number of useful bug reports.

**Comment by gr-sp** [comment]
I hear the sarcasm. It isn't lost on me. :)

**Comment by mbr0wn** [comment]
I was serious, actually :)

**Pull request merged**
