### PR TITLE
Added new packager macports

### PR DESCRIPTION
**Pull request by sbmueller**
Added packager for macports (see #232).
Recipe updates are in the work!

### CODE REVIEW

**Comment by mbr0wn** [comment]
@sdh11 please review.

**Comment by sdh11** [comment]
I will try to get to this tomorrow or Wednesday.

**Comment by mbr0wn** [comment]
@sdh11 If this is OK, please go ahead and merge straight into master.

**Comment by mbr0wn** [comment]
@sbmueller Looks like you'll need to fix some merge conflicts though.

**Comment by sbmueller** [comment]
Sorry, I don't have access to my productive laptop right now. I can have a look at the weekend.

**Comment by mbr0wn** [comment]
No hurry, @sdh11 still needs to review :)

**Comment by sdh11** [comment]
The packager looks fine, but I'm running into multiple issues installing on a 10.11 system. Most seem to be quick fixes to the recipes, which need to be resolved before this gets merged. I will comment on the recipes PR once I get it installing.

**Comment by sbmueller** [comment]
Hi @sdh11 thanks for having a look!
I have experienced correct behaviour when installing `cmake` through pybombs. But as you mentioned, GNU Radio installation fails, because not all dependencies are available through port. In this case, pybombs falls back to compiling from source, which fails on my 10.11 system. For instance is this the case for the dependency `alsa`, which is actually not available for OS X according to my research.

**Comment by sdh11** [comment]
Yes, `alsa` is the Advanced Linux Sound Architecture, so it is Linux dependent. We will need to make some changes to either the packager or pybombs to support distribution specific dependencies. But, I want to resolve all the other recipe issues first before addressing that. My current solution is just removing `alsa` from the prefix's gnuradio recipe.

**Comment by mbr0wn** [comment]
One thing you can do to disable alsa for Mac is to put a macports satisfier line into the alsa recipe, and then put in something that is guaranteed to exist. Otherwise, removing alsa until we've figured out a way to get this going is fine.

**Comment by sbmueller** [comment]
I used @mbr0wn s workaround (now vim is installed instead of alsa :P), but I'm afraid there are many more similar issues to come. The next error I get is UHD. Pybombs tells me in verbose mode, that "Package uhd is requesting a source build." Building fails on OS X, so is there a reason to not install this with a package manager (port has V 3.9.3 of UHD)? I'm not sure how to disable source building in the recipe though.

**Comment by mbr0wn** [comment]
@sbmueller OOTs and hardware default to source builds. You can change your local `.pybombs/config.yml` and add this line:
```{.yaml}
packages:
  uhd:
    forcebuild: False
```

or even:
```{.yaml}
categories:
  hardware:
    forcebuild: False
```

**Comment by mbr0wn** [comment]
Also, why does UHD build fail? Is that something we need to fix, or is that a local issue?

**Comment by mbr0wn** [comment]
@sbmueller 67d45373b78d88c8cc53d679015f9c7d5b3cf018 adds a feature where you can disable alsa for macports. Edit alsa.lwr as such:
```{.yaml}
satisfy:
  port: True
```

**Comment by sbmueller** [comment]
Thanks @mbr0wn for helping. Building UHD fails with the following output
```bash
PyBombs.Packager.source - DEBUG - Using build directory: /Users/senpo/gnuradio/src/uhd/build
PyBombs.Packager.source - WARNING - Build dir already exists: /Users/senpo/gnuradio/src/uhd/build
PyBombs.Packager.source - DEBUG - Configuring recipe uhd
PyBombs.Packager.source - DEBUG - Using vars - {'config_opt': '', 'builddir': '/Users/senpo/gnuradio/src/uhd/build'}
PyBombs.Packager.source - DEBUG - In cwd - /Users/senpo/gnuradio/src/uhd/build
PyBombs._process_thread() - DEBUG - Executing command `CC= CXX= cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/Users/senpo/gnuradio  -Wno-dev'
Configuring: (100%) [=====================================================================================================================================================================================]
PyBombs.monitor_process() - DEBUG - Thread signaled termination or returned
PyBombs.monitor_process() - DEBUG - Return value: 1
```

As far as I know, UHD should be built in the /uhd/host/build directory, but pybombs seems to use /uhd/build instead. There, `cmake` cannot find a CMakeLists.txt in the parent directory:
```bash
CMake Error: The source directory "/Users/senpo/gnuradio/src/uhd" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

So there is actually an error if I haven't missed anything. If I am right, we can maybe deal with this in a separate issue.
I will try to build UHD by hand and let you know if I get it working. For this PR, I will change UHD to be installed via ports so we can move on here.

**Comment by sbmueller** [comment]
Building UHD from the /uhd/host/build directory works for me, but the cmake command has to be modified as follows:
```bash
CC= CXX= cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/Users/senpo/gnuradio -DPYTHON_LIBRARIES=/opt/local/lib/libpython2.7.dylib -DPYTHON_EXECUTABLE:FILEPATH=/opt/local/bin/python2.7  -Wno-dev
```
The python libraries and executable need to be specified, as OS X has it's own system standard python instance. When installing python modules with port, they get only installed for the macports python instance (with prefix `/opt/local`). Maybe there is already a possibility to set this paths in pybombs?

**Comment by sdh11** [comment]
@mbr0wn I think this is the same as the #302 issue.

**Comment by sbmueller** [comment]
Building GNU Radio from source fails as well. First, I get `library not found for -lgsl`, so I added `/opt/local/lib` to the `CMAKE_LIBRARY_PATH`. After that, I really can't figure out the problem in the following output of `make -d -j4`:
```bash
Must remake target `gr-filter/lib/CMakeFiles/gnuradio-filter.dir/build'.
Successfully remade target file `gr-filter/lib/CMakeFiles/gnuradio-filter.dir/build'.
Reaping winning child 0x7fa712e278d0 PID 14329
Live child 0x7fa712e278d0 (gr-filter/lib/CMakeFiles/gnuradio-filter.dir/all) PID 14347
[ 81%] Built target gnuradio-filter
Reaping winning child 0x7fa712e278d0 PID 14347
Removing child 0x7fa712e278d0 PID 14347 from chain.
Reaping losing child 0x7f89db40a6c0 PID 12969
make: *** [all] Error 2
Removing child 0x7f89db40a6c0 PID 12969 from chain.
```

**Comment by mbr0wn** [comment]
@sbmueller That UHD build issue was fixed in 38ed9d169ed67ef090e6015b07c4918f7c112209

**Comment by sbmueller** [comment]
Thanks @mbr0wn , I merged your commit into my pybombs source, but still the python path issue persists.

**Comment by sdh11** [comment]
I suspect we will need to add the ability to specify non standard paths for dependencies. Homebrew also does something similar. I plan to work on that tomorrow.

**Comment by mbr0wn** [comment]
The Python path thing looks like it can be handled on a `config.yml` basis. You can globally set `$config_opts` to include those `-DFOO` settings for gnuradio, hardware and oots.

**Comment by mbr0wn** [comment]
I think with #292 we can simply work out something for Mac systems, so the PYTHONPATH defaults are set correctly for Macs.

Also, you can use the `env:` section to set stuff up for you.

**Comment by sbmueller** [comment]
I can confirm UHD builds fine out of pybombs with these lines in the `config.yml`:
```yml
packages:
  uhd:
    forcebuild: true
    vars:
      config_opt: ' -DPYTHON_LIBRARIES=/opt/local/lib/libpython2.7.dylib -DPYTHON_EXECUTABLE:FILEPATH=/opt/local/bin/python2.7 '
```

Still GNURadio has build problems: `ld: library not found for -lgsl`. GSL is installed and it's library is located in `/opt/local/lib`. Also, this directory was appended to the `DYLD_LIBRARY_PATH`. When configuring, cmake seems to find the library, but linking fails at 77%.

**Comment by mbr0wn** [comment]
@sbmueller @sdh11 I'm happy to merge this if the actual packager works, even if GNU Radio installs don't. So, pick an easy recipe, add the macports satisfier, and then make sure these work:
```
$ pybombs recipes list -l YOUR_PACKET
$ pybombs install YOUR_PACKET
$ pybombs remove YOUR_PACKET
```

We can then figure out the GNU Radio installation issues. However, the actual packager itself must be a-OK before merging.

**Comment by sdh11** [comment]
@mbr0wn I haven't had any issues with the packager itself, so good to go. It doesn't uninstall through macports, but that is consistent with apt-get and yum. 

The issues I am running into are recipe conflicts. From a clean system, port complains about conflicting packages when installing some dependencies. If I already have GR installed through macports, then it makes it to the builds without the conflicts.

**Comment by sbmueller** [comment]
`pybombs recipes list -l cmake` results to 
```bash
Loading package information....

Package Name  Recipe Filename                          Installed By
---------------------------------------------------------------------
cmake         ~/.pybombs/recipes/gr-recipes/cmake.lwr  port
```
After removing cmake, `pybombs install cmake` results to
```bash
|
\- cmake
PyBombs.install - INFO - Installing package: cmake
--->  Computing dependencies for cmake
--->  Fetching archive for cmake
--->  Attempting to fetch cmake-3.5.2_0.darwin_15.x86_64.tbz2 from https://packages.macports.org/cmake
--->  Attempting to fetch cmake-3.5.2_0.darwin_15.x86_64.tbz2.rmd160 from https://packages.macports.org/cmake
--->  Installing cmake @3.5.2_0
--->  Activating cmake @3.5.2_0
--->  Cleaning cmake
--->  Updating database of binaries
--->  Scanning binaries for linking errors
--->  No broken files found.
PyBombs.install - INFO - Installation successful.
```
Removing does not work as  @sdh11 mentioned, because pybombs seems to fall back to packager "source" and then is unable to find the specified package. 
If this is ok with you, I still have to fix some merge conflicts again with the recipes. I will do that in the next days. But I think we can already merge here because the packager won't be used until the recipes are merged as well.

**Comment by michaelld** [comment]
If CMake is complaining that a library isn't being found, then it's most likely not being included correctly in the CMakeLists.txt file for wherever the linking is being done. The correct solution is probably not to add "-L..." to LIBRARY_FLAGS or CXX_FLAGS, but rather to use the CMake commands "link_directories(...)" and "target_link_libraries(...)" to fix the actual issue. These latter are the CMake way of doing things.

A few CMake versions back, the above were roughly equivalent. Current CMake actually tries to resolve all of the libraries being used and reference them directly instead of using "-L... -l...". By referencing them directly without adding in any extra -L... directories to search through, the linker is forced to either succeed or fail in linking without extra searching. This feature is good in a general sense, because it provides immediate feedback as to whether the library was found / linked against or not.

In this case, because linking is failing that means most likely that the CMake scripts aren't written property, not that the library isn't there.

That said, I'll admit that I haven't read through the whole PR discussion here, just snippets of it. Maybe I missed something?

**Pull request merged**
