### PR TITLE
pass c++ compiler as CPP and CXX -- since they both seem to be used s…

### PR DESCRIPTION
**Pull request by osh**
…ome places

### CODE REVIEW

**Comment by mbr0wn** [comment]
What are your thoughts on removing CC= and CPP= from this line entirely? From your config.yml, you can set any environment variable anyway.

**Comment by osh** [comment]
i dont like it :-(
you should be able to set these once and each build process should be responsible for transferring them however into cmake, autotools, distutils or whatever needs them 
otherwise might need to set a dozen mystical env vars

**Comment by osh** [comment]
this is a critical pybombs feature we do not want to deprecate

**Comment by mbr0wn** [comment]
Not sure if we're talking about the same thing here. With your stuff, the config.yml looks like this:
```{.yaml}
config:
  cxx: gcc
```

What I'm suggesting is to just put the CXX and CPP vars into config.yml:
```{.yaml}
env:
  CXX: gcc
```

This is the same amount of configuration overhead, and it has the same effect. However, it removes the `CXX= CPP= CC=` from every call to cmake, which has caused issues for the cross-compile environments.
Also, the env variable names are well-established now. The PyBOMBS config variable names are random choices we made.

**Comment by mbr0wn** [comment]
ba546d0f174244d485febac5cd6e2b20b249449d obviates this.

**Pull request closed without merging**
