### PR TITLE
Added configuration option to disable progress bar

### PR DESCRIPTION
**Pull request by marcusmueller**
When remotely running pybombs, progress updates are the opposite of useful.
So: added a config file option to disable them

### CODE REVIEW

**Comment by mbr0wn** [comment]
Why do you think we need this? Also, you're only changing the wget fetcher. Is this on purpose? What about the oprocs?

**Comment by marcusmueller** [comment]
Reasons:

*  `--quiet` doesn't disable progress bars (which is imho non-intuitive) (I just realized I haven't implemented actually reacting to `--quiet`)
* when running pybombs via SSH on a VM, capturing it's output I've gotten long strings of the pattern `(00%)\008(00%)\008(01%)…` which made reading the output very hard

Only wget: that was the most "obnoxious" one of them, but yeah, I'll work on the git fetcher, too, and the configure and build progress bars. Am I missing any progress bar?

**Comment by mbr0wn** [comment]
As you might have noticed, the wget fetcher progress bar has that 'TODO' in there for putting it into an output processor. Those, btw, work across ssh. So if we fix this TODO, will this fix your issue?

**Comment by marcusmueller** [comment]
probably. At any rate, it was a bad idea then to fix it here.

**Pull request closed without merging**
