### PR TITLE
Remove Ubuntu 14.04 & 16.04, and fix Ubuntu 18.04

### PR DESCRIPTION
**Pull request by argilo**
Ubuntu 14.04 and 16.04 won't work anymore, because libvolk now has a minimum cmake version of 3.8.

Ubuntu 18.04 (Python 2 & Python 3) need a timezone to be set. I've copied in the necessary lines from the Ubuntu 20.04 Dockerfile.

### CODE REVIEW

**Review by jkbecker — APPROVED** [review]
looking good 👍

**Comment by argilo** [comment]
As before I'm still waiting for builds to finish. Assuming all goes well, I'll merge tomorrow morning.

**Comment by argilo** [comment]
Ubuntu 18.04 with Python 2 is still not working, because PyBOMBS installs Python 2 dependencies, and GNU Radio tries to build with Python 3. But I'll merge this anyway, since it's a pre-existing problem that probably needs to be fixed in the GNU Radio recipe (if we still care about Python 2 -- many people in the Development channel thought PyBOMBS may as well drop Python 2 support).

**Comment by jkbecker** [comment]
Personally, I agree with getting rid of py2 support (maybe do a proper version bump to clean up?)... it would probably reduce code complexity a lot, and most definitely install edge cases & quirks.
We could create an issue worded as a request for comments on this and ask people in the dev chat to chime in on this as an issue comment if they have any reservations, just to collect what kinds of other opinions are out there?

**Pull request merged**
